version: '3.7'
services:
  oplearn:
    build:
      context: .
    volumes:
      - .:/home/user/oplearn
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
      - MUJOCO_GL=egl
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - "/dev:/dev"
    privileged: true
    stdin_open: true
    tty: true
    runtime: nvidia

