version: '3.7'
services:
  cyclic_lxm:
    build:
      context: .
    volumes:
      - .:/cyclic_lxm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/docker.xauth
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./volume/vscode-server:$HOME/.vscode-server
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/docker.xauth
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
      - MUJOCO_GL=egl
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - "/dev:/dev"
    privileged: true
    stdin_open: true
    tty: true
    runtime: nvidia
    network_mode: host


